# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  #encoding: unicode
  database: trs
  pool: 5
  username: trs
  password: trs  ### password you have specified within psql
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: d3rgv31t11asr2
  host: ec2-23-21-249-224.compute-1.amazonaws.com
  port: 5432
  pool: 5
  username: unvostozfwesbn
  password: rPzRZ3KORMc_c87ONXjkR7qmGT